### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by Pyxidatol-C** [Pyxidatol-C/Xample#1]
Changes made to the interface (caching as json, args passed to command) need to be reflected in README.

**Comment by Pyxidatol-C** [comment]
merci bene

**Comment by TrakJohnson** [comment]
Oki doki

**Comment by Pyxidatol-C** [comment]
Inconsistencies to fix: archaic “solution.py”
The “\n” at the end is needed to terminate the inputs.

**Comment by TrakJohnson** [comment]
Mais euh tu sais pas lire ou quoi ! 8b711b74f82d7e4177a4e7e2f3ad720be0dc984a
